### ISSUE TITLE
Stackoverflow exception while generating json

### ISSUE THREAD

**Issue by rahimlis** [linsage/java2json#6]
While i am trying to convert following object plugin throws stackoverflow exception

  
    private String customerId;

    private LocalDate activationDate;

    private String chargeAccountId;

    private String chargeCode;

    private BundleChargeCode nextChargeCode;

    private BigDecimal monthlyFee;

    private String monthlyFeeCurrency;

    private String bundleRemark;

Here bundleChargecode is just enum

```
java.lang.StackOverflowError
	at com.intellij.util.containers.ConcurrentWeakKeySoftValueHashMap.createHardKey(ConcurrentWeakKeySoftValueHashMap.java:213)
	at com.intellij.util.containers.ConcurrentWeakKeySoftValueHashMap.get(ConcurrentWeakKeySoftValueHashMap.java:222)
	at com.intellij.util.containers.ConcurrentFactoryMap.get(ConcurrentFactoryMap.java:56)
	at com.intellij.psi.impl.file.impl.ResolveScopeManagerImpl.getResolveScopeFromProviders(ResolveScopeManagerImpl.java:62)
	at com.intellij.psi.impl.file.impl.ResolveScopeManagerImpl.getResolveScope(ResolveScopeManagerImpl.java:124)
	at com.intellij.psi.impl.ResolveScopeManager.getElementResolveScope(ResolveScopeManager.java:51)
	at com.intellij.psi.impl.PsiElementBase.getResolveScope(PsiElementBase.java:184)
	at com.intellij.psi.impl.PsiClassImplUtil.getMap(PsiClassImplUtil.java:207)
	at com.intellij.psi.impl.PsiClassImplUtil.getAllWithSubstitutorsByMap(PsiClassImplUtil.java:183)
	at com.intellij.psi.impl.PsiClassImplUtil.getAllByMap(PsiClassImplUtil.java:188)
	at com.intellij.psi.impl.PsiClassImplUtil.getAllFields(PsiClassImplUtil.java:72)
	at com.intellij.psi.impl.compiled.ClsClassImpl.getAllFields(ClsClassImpl.java:259)
	at com.linsage.Java2JsonAction.getFields(Java2JsonAction.java:76)
	at com.linsage.Java2JsonAction.getFields(Java2JsonAction.java:116)
	at com.linsage.Java2JsonAction.getFields(Java2JsonAction.java:116)
	at com.linsage.Java2JsonAction.getFields(Java2JsonAction.java:116)
	at com.linsage.Java2JsonAction.getFields(Java2JsonAction.java:116)
	at com.linsage.Java2JsonAction.getFields(Java2JsonAction.java:116)
	at com.linsage.Java2JsonAction.getFields(Java2JsonAction.java:116)
```

**Comment by linsage** [comment]
fix it , version 1.0.4
